[book]
authors = ["upup1251"]
language = "en"
multilingual = false
src = "src"
title = "Computer composition principles and assembly"

[output.html]
right-sidebar = true

[preprocessor.toc]
command = "mdbook-toc"  
renderer = ["html"]
marker = "[toc]"  # 目录占位符

[preprocessor.katex]

