[book]
authors = ["upup1251"]
language = "en"
multilingual = false
src = "src"
title = "Principles and Design of Databases"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "[toc]"
